// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC92KLbOeFkq3jUFCi1e1xBNuEBpbDtYc',
    appId: '1:524253465196:web:d701ebe544fdb6ff2be649',
    messagingSenderId: '524253465196',
    projectId: 'sportify-8f1ec',
    authDomain: 'sportify-8f1ec.firebaseapp.com',
    storageBucket: 'sportify-8f1ec.appspot.com',
    measurementId: 'G-7B4WWKT7WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtbjgh48cFv4F6RPo_Di93o3RD413zko',
    appId: '1:524253465196:android:c5b5182e5ee0610b2be649',
    messagingSenderId: '524253465196',
    projectId: 'sportify-8f1ec',
    storageBucket: 'sportify-8f1ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF-u0_7NC0y8dENAFedNNywgG2_7IWlfg',
    appId: '1:524253465196:ios:3ca49acc73861e9c2be649',
    messagingSenderId: '524253465196',
    projectId: 'sportify-8f1ec',
    storageBucket: 'sportify-8f1ec.appspot.com',
    iosBundleId: 'com.example.sportify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF-u0_7NC0y8dENAFedNNywgG2_7IWlfg',
    appId: '1:524253465196:ios:9a52f7530ed51b942be649',
    messagingSenderId: '524253465196',
    projectId: 'sportify-8f1ec',
    storageBucket: 'sportify-8f1ec.appspot.com',
    iosBundleId: 'com.example.sportify.RunnerTests',
  );
}
